[package]
name = "scargo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "*", features = ["derive"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
toml = "*"
dirs = "*"
anyhow = "*"
tokio = { version = "*", features = ["full"] }
toml_edit = "0.22"
reqwest = { version = "*", features = ["json"] }
