[package]
name = "hello"
version = "0.1.0"
main = "Main"
scala_version = "2.13"
source_dir = "src/main/scala"
target_dir = "build"

[dependencies]

"org.typelevel::cats-core_2.13" = "2.13.0"

"org.scalafx::scalafx_2.12" = "24.0.2-R36"